// src/redux/actionTypes.js
export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const SET_SELECTED_ITEMS = "SET_SELECTED_ITEMS";
export const SET_MEAL_TYPE = "SET_MEAL_TYPE";
export const SET_FOOD_CHOICES = "SET_FOOD_CHOICES";
export const SET_CALORIES = "SET_CALORIES";
export const SET_NUTRITION = "SET_NUTRITION";
export const SET_NUTRITION_DATA = "SET_NUTRITION_DATA";
export const SET_FOOD_LOGS = "SET_FOOD_LOGS";
export const SET_NUTRITION_SUMMARY = "SET_NUTRITION_SUMMARY";

